version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run: name: deps command: make deps
      - run: name: lint command: make lint
      - run: name: test command: make test
      - run: name: docker_build command: make docker_build
      - run: name: docker_push command: make docker_push
workflows:
  zaliczenie:
    jobs:
      - build-and-test
